version: '3'

services:
  nodejs-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - promtail

  promtail:
    image: grafana/promtail:latest
    volumes:
      - ./promtail-config:/etc/promtail
    command: -config.file=/etc/promtail/promtail-config.yml

  loki:
    image: grafana/loki:latest
    ports:
      - "3100:3100"
    volumes:
      - ./loki-config:/etc/loki

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - loki
